name: "\U0001F680 Feature request"
description: Submit a request for a new feature
labels: ["enhancement", "pending"]
body:
  - type: markdown
    attributes:
      value: |        
        Thank you for taking the time to suggest a new feature for MemOS! To help us understand and evaluate your proposal, please provide detailed information below.
        
        感谢您为 MemOS 提出新功能建议！为了帮助我们理解和评估您的提案，请在下方提供详细信息。

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      description: Please confirm you have completed these steps
      options:
        - label: I have searched existing issues and this feature hasn't been requested before | 我已搜索现有问题，确认此功能尚未被请求
          required: true
        - label: I have read the project documentation and confirmed this feature doesn't already exist | 我已阅读项目文档并确认此功能尚未存在
          required: true
        - label: This feature request is specific to MemOS and not a general software issue | 该功能请求是针对 MemOS 的，而不是一般软件问题
          required: true

  - type: textarea
    id: problem
    validations:
      required: true
    attributes:
      label: Problem Statement
      description: |
        What problem does this feature solve? What pain point are you experiencing? | 该功能解决什么问题？您遇到了什么痛点？
      placeholder: |
        Describe the problem you're trying to solve...
        Example: "As a developer using MemOS, I find it difficult to..."

  - type: textarea
    id: proposed_solution
    validations:
      required: false
    attributes:
      label: Proposed Solution
      description: |
        Describe your proposed solution in detail. How would this feature work? | 描述您提议的解决方案。这个功能将如何工作？
      placeholder: |
        Describe your proposed solution...
        Include:
        - How it would work
        - What the API/interface might look like
        - Any technical considerations

  - type: textarea
    id: contribution
    validations:
      required: false
    attributes:
      label: Implementation Contribution
      description: |
        Are you willing to contribute to the implementation of this feature? | 您是否愿意为此功能的实现做出贡献？
      placeholder: |
        - [ ] I'm willing to implement this feature myself
        - [ ] I can help with testing
        - [ ] I can help with documentation
        - [ ] I can provide guidance/requirements but cannot implement
        - [ ] I would like someone else to implement this
